### ISSUE TITLE
factory tests

### ISSUE THREAD

**Issue by ethers** [androlo/sol-unit#3]
do you have samples of testing factories and interaction with the contracts the factories create?

also, is any of this code on github?
https://eng.erisindustries.com/tutorials/2015/03/11/solidity-1

thanks

**Comment by compleatang** [comment]
that code's in the eris repos under solidity-resources AFAIK.

**Comment by ethers** [comment]
thanks, though I don't find any repos named solidity in https://github.com/eris-ltd

**Comment by compleatang** [comment]
ah. yeah. sorry. looks like andreas moved it somewhere else. used to be in there.
